/** Slash commands available in the composer (shared by the picker and the docs). */
export interface Command { id: string; icon: string; label: string; hint: string }
export const COMMANDS: Command[] = [
  { id: "research", icon: "🔬", label: "/research", hint: "Deep research with sources" },
  { id: "arena", icon: "⚔️", label: "/arena", hint: "Compare several providers side by side" },
  { id: "image", icon: "🎨", label: "/image", hint: "Generate an image in the Studio" },
  { id: "debate", icon: "🥊", label: "/debate", hint: "Two agents argue a motion, Metis judges — /debate <motion>" },
  { id: "explain", icon: "🔍", label: "/explain", hint: "Explain the last answer: reasoning, confidence, what could be wrong, how to verify" },
  { id: "ethics", icon: "⚖️", label: "/ethics", hint: "AI ethics impact assessment — /ethics <plan, feature or text>" },
  { id: "control", icon: "🎛️", label: "/control", hint: "Control Center — system health, capability registry, events, permissions" },
  { id: "schedules", icon: "⏰", label: "/schedules", hint: "Scheduled automations — daily digests, weekly reports, reminders" },
  { id: "docs", icon: "📁", label: "/docs", hint: "Chat with your documents — upload PDF/DOCX/CSV and get cited answers" },
  { id: "voice", icon: "🎙", label: "/voice", hint: "Hands-free voice conversation (speak & listen) in English, Tamil, Hindi…" },
  { id: "study", icon: "🎓", label: "/study", hint: "Quizzes & flashcards with spaced repetition, generated by tutor agents" },
  { id: "learn", icon: "📚", label: "/learn", hint: "Explained AI: plain-language concepts, limits and ethics" },
  { id: "workflows", icon: "⛓️", label: "/workflows", hint: "Chain agents into automations" },
  { id: "room", icon: "👥", label: "/room", hint: "Open a live room for this chat" },
  { id: "share", icon: "🔗", label: "/share", hint: "Create a public link to this chat" },
  { id: "new", icon: "✨", label: "/new", hint: "Start a new chat" },
  { id: "agents", icon: "🤖", label: "/agents", hint: "Browse all agents" },
  { id: "gallery", icon: "🗂️", label: "/gallery", hint: "Prompt & agent gallery" },
  { id: "settings", icon: "⚙️", label: "/settings", hint: "Open settings" },
  { id: "export", icon: "⤓", label: "/export", hint: "Download this chat as Markdown" },
];
