/**
 * Built-in capability sources. Each adapts an existing Aetheris catalog into Capability records.
 * The "platform" source is the honest status board for whole subsystems — including the ones that
 * are only partially built (robotics, twins). Nothing here is mocked; the `simulated` device adapter is labelled as such.
 */
import type { Capability, CapabilitySource } from "./types";
import { registerSource } from "./registry";
import { allProviders, isConfigured, resolveModel } from "@/aetheris/lib/router/providers";
import { meshStatus } from "@/aetheris/lib/router/router";
import { AGENTS } from "@/aetheris/lib/agents/catalog";
import { CONNECTORS } from "@/aetheris/lib/mcp/catalog";
import { APIS } from "@/aetheris/lib/gateway/apis";
import { store } from "@/aetheris/lib/store";
import type { McpServerRecord } from "@/aetheris/core/mcp/gateway";

// ---- Models --------------------------------------------------------------------------------------
const modelSource: CapabilitySource = {
  id: "models",
  list() {
    const mesh = new Map(meshStatus().map((m) => [m.id, m]));
    return allProviders().map<Capability>((p) => {
      const m = mesh.get(p.id); const total = (m?.successes ?? 0) + (m?.failures ?? 0);
      return {
        id: `model:${p.id}`, name: `${p.name} · ${resolveModel(p)}`, category: "model", provider: "router",
        description: p.notes ?? `${p.name} via ${p.kind} adapter`, status: isConfigured(p) ? "implemented" : "not_available",
        tags: ["llm", "chat", p.kind, ...(p.vision ? ["vision", "multimodal"] : []), ...(p.keyless ? ["keyless"] : []), p.id],
        security_level: "read_only", cost: { unit: "free" }, latency: "normal",
        reliability: total ? (m!.successes + 1) / (total + 2) : undefined,
        model_requirements: undefined, supported_operations: ["chat.completions", "stream", ...(p.vision ? ["vision"] : [])],
        verification_status: total ? "verified" : "unverified", locality: "remote", invoke: { kind: "internal", ref: "router.route({preferred})" },
      };
    });
  },
};

// ---- Agents --------------------------------------------------------------------------------------
const agentSource: CapabilitySource = {
  id: "agents",
  list: () => AGENTS.map<Capability>((a) => ({
    id: `agent:${a.id}`, name: `${a.icon} ${a.name}`, category: "agent", provider: "orchestrator", description: a.description, status: "implemented",
    tags: [a.domain, a.tier, ...a.skills.map((s) => s.toLowerCase()), ...(a.aliases ?? [])],
    security_level: "read_only", cost: { unit: "free" }, latency: "normal", supported_operations: ["run", "delegate"], verification_status: "verified", locality: "remote",
    invoke: { kind: "mention", ref: `@${a.id}` },
  })),
};

// ---- Connectors (remote MCP + gateway REST) -----------------------------------------------------
const connectorSource: CapabilitySource = {
  id: "connectors",
  list: () => [
    ...CONNECTORS.map<Capability>((c) => ({
      id: `connector:${c.id}`, name: c.name, category: "connector", provider: c.kind === "remote" ? "mcp-remote" : "gateway", description: c.description,
      status: c.kind === "gateway" ? "implemented" : "partial", // remote servers: real, but reachability depends on vendor + user credential
      tags: [c.category, c.kind, "mcp", ...(c.auth ? ["needs-credential"] : ["public"])],
      security_level: /write|send|create|post|delete/i.test(c.description) ? "safe_write" : "read_only", cost: { unit: "free" }, latency: "fast",
      supported_operations: ["tools/list", "tools/call"], verification_status: "untestable_here", locality: "remote", invoke: { kind: "mcp", ref: c.kind === "remote" ? c.url : `/api/gateway/${c.id}` },
    })),
    ...APIS.flatMap<Capability>((api) => api.tools.map((t) => ({
      id: `tool:${api.id}.${t.name}`, name: `${api.name}: ${t.name}`, category: "tool", provider: "gateway", description: t.description, status: "implemented",
      tags: [api.id, ...t.name.split("_")], input_schema: { type: "object", properties: Object.fromEntries(Object.entries(t.params ?? {}).map(([k, v]) => [k, { type: v.type, description: v.description }])), required: Object.entries(t.params ?? {}).filter(([, v]) => v.required).map(([k]) => k) },
      security_level: /^(send|create|post|add|update|delete|remove|set|write|publish|upload)/.test(t.name) ? "safe_write" : "read_only", requires_confirmation: /^(delete|remove)/.test(t.name),
      cost: { unit: "free" }, latency: "fast", supported_operations: ["call"], verification_status: "untestable_here", locality: "remote", invoke: { kind: "mcp", ref: `${api.id}__${t.name}` },
    }))),
  ],
};

// ---- Platform subsystems (honest status board) --------------------------------------------------
const P = (c: Omit<Capability, "cost" | "latency" | "locality" | "provider"> & Partial<Pick<Capability, "cost" | "latency" | "locality" | "provider">>): Capability =>
  ({ cost: { unit: "free" }, latency: "normal", locality: "hybrid", provider: "aetheris-core", ...c });

const platformSource: CapabilitySource = {
  id: "platform",
  list: () => [
    P({ id: "system:model-router", name: "Model Router (task-aware, local-first capable)", category: "system", description: "Provider-neutral router over 27 cloud + 3 local providers (Ollama, LM Studio, vLLM/custom): task policy (coding/reasoning/long-context/multilingual/tools), locality (local/prefer_local/remote), context fit, health-ranked failover, cooldowns, streaming.", status: "implemented", tags: ["router", "failover", "models", "local", "ollama"], security_level: "read_only", supported_operations: ["route", "stream", "failover"], verification_status: "verified" }),
    P({ id: "system:agent-runtime", name: "Agent Runtime (jobs, budgets, checkpoints)", category: "system", description: "Prime plans, specialists execute single/pipeline/parallel, Metis extracts lessons; background jobs with budgets (model calls, chars, time, agents), checkpoints, cancellation, retry, SSE progress (/api/jobs).", status: "implemented", tags: ["agents", "planner", "executor"], security_level: "read_only", supported_operations: ["plan", "delegate", "pipeline", "parallel", "reflect"], verification_status: "verified" }),
    P({ id: "system:characters", name: "Character Database", category: "system", description: "Persistent, owner-scoped AI personas with create/edit/delete, curated deity interpretations across four traditions, and separate transparent roleplay and educational guide modes. Character system prompts are resolved server-side by id. /api/characters.", status: "implemented", tags: ["characters", "personas", "mythology", "roleplay", "education"], security_level: "safe_write", supported_operations: ["browse", "create", "update", "delete", "chat", "roleplay", "guide"], verification_status: "verified", locality: "local" }),
    P({ id: "system:verifier", name: "Verification Engine", category: "system", description: "Explainer/critic pass (fact vs inference, confidence, how to verify) plus three real gates: JSON-schema validation of model/tool output, an independent reviewer that is routed to a different provider than the generator (and reports independent:false when it could not be), and a test loop that runs a command in the execution sandbox and feeds the failure back to a revise step, up to 6 iterations. /api/verify. Missing: no container isolation for the loop (sandbox is process-level) and no persistent verdict store.", status: "implemented", tags: ["verify", "review", "explainability", "schema", "tests"], security_level: "safe_write", supported_operations: ["explain", "critique", "validate", "review", "test"], verification_status: "verified" }),
    P({ id: "system:execution-policy", name: "Execution Policy & Permissions", category: "execution", description: "Capability-based permission levels (READ_ONLY → PHYSICAL), confirmation gates and audit log for every tool/command invocation.", status: "implemented", tags: ["security", "permissions", "sandbox", "audit"], security_level: "admin", supported_operations: ["check", "audit"], verification_status: "verified" }),
    P({ id: "execution:browser-sandbox", name: "Code Interpreter (browser sandbox)", category: "execution", description: "Python (Pyodide) and JavaScript run inside a sandboxed iframe in the user's browser — no server execution.", status: "implemented", tags: ["python", "javascript", "sandbox"], security_level: "read_only", supported_operations: ["run"], verification_status: "verified", locality: "local" }),
    P({ id: "execution:server-sandbox", name: "Server-side command sandbox", category: "execution", description: "Process-isolated shell/test execution on the server: fresh temp workspace, scrubbed env, SIGKILL timeout, output caps, allow-listed binaries, deny-list, network off via unshare when the host permits. Not a VM/container — run Aetheris itself in a container for defence in depth.", status: "implemented", tags: ["shell", "tests", "python", "node", "sandbox"], security_level: "full_workspace", requires_confirmation: true, supported_operations: ["run", "files", "fsChanges"], verification_status: "verified", locality: "local" }),
    P({ id: "system:mcp-gateway", name: "MCP Gateway & Hub", category: "system", description: "One MCP endpoint (/api/mcp/hub) aggregating 110 catalog connectors (remote MCP + REST gateway, per-user credentials, OAuth) plus user-registered MCP servers (/api/mcp/servers) with manifest capture, health monitoring & sweeps, tool versioning, JSON-schema argument validation and per-tool permission classification.", status: "implemented", tags: ["mcp", "tools", "gateway"], security_level: "safe_write", supported_operations: ["tools/list", "tools/call", "oauth"], verification_status: "verified" }),
    P({ id: "system:capability-registry", name: "Capability Registry", category: "system", description: "Unified, searchable metadata for models, agents, tools, connectors, subsystems with honest status. Drives intent routing and the Control Center.", status: "implemented", tags: ["registry", "discovery"], security_level: "read_only", supported_operations: ["search", "get", "summary"], verification_status: "verified", locality: "local" }),
    P({ id: "system:intent-router", name: "Intent → Capability Router", category: "system", description: "Classifies a command into task types and picks capabilities (agent, connectors, knowledge, mode) with explicit manual override.", status: "implemented", tags: ["intent", "routing", "planner"], security_level: "read_only", supported_operations: ["route"], verification_status: "verified", locality: "local" }),
    P({ id: "knowledge:fabric", name: "Knowledge Fabric (hybrid: keyword + vector + graph + temporal)", category: "knowledge", description: "SQLite/FTS5 fact store with provenance per fact and edge, entity/relation graph, point-in-time (asOf) queries with supersession, reciprocal-rank fusion of BM25 + cosine + graph expansion. Embeddings: corpus-trained offline semantic vectors by default (Random Indexing over the stored facts — no network, no model file), falling back to a lexical hashed n-gram until the corpus has taught it something; set EMBEDDINGS_URL/KEY to prefer a provider. Every vector is tagged with its space so only comparable vectors are matched. /api/knowledge, /api/knowledge/graph. Auto-recalled into chat.", status: "implemented", tags: ["knowledge", "graph", "vector", "temporal", "provenance"], security_level: "safe_write", supported_operations: ["add", "query", "graph", "delete"], verification_status: "verified", locality: "local" }),
    P({ id: "knowledge:kb", name: "Knowledge bases (documents, BM25)", category: "knowledge", description: "Per-user KBs: PDF/DOCX/CSV/HTML/text/URL ingestion, heading-aware chunking, BM25 retrieval, [D#] citations. Structured facts live in knowledge:fabric.", status: "implemented", tags: ["rag", "documents", "pdf", "citations"], security_level: "read_only", supported_operations: ["ingest", "search", "cite"], verification_status: "verified", locality: "local" }),
    P({ id: "memory:typed", name: "Typed memory (episodic / semantic / procedural / working / short-term)", category: "memory", description: "Server-side per-user memory on the knowledge fabric: provenance, confidence, dedupe, eviction limits, supersession, hybrid time-scoped recall; working & short-term are process-local (not persisted). /api/memory. Auto-recalled into chat.", status: "implemented", tags: ["memory", "episodic", "semantic", "procedural"], security_level: "safe_write", supported_operations: ["remember", "recall", "list", "forget"], verification_status: "verified", locality: "local" }),
    P({ id: "memory:user", name: "Memory (client facts, agent lessons)", category: "memory", description: "Client-stored user memory with LLM extraction, review, deletion; Metis agent lessons per user. Complements memory:typed.", status: "implemented", tags: ["memory"], security_level: "read_only", supported_operations: ["extract", "list", "forget"], verification_status: "verified", locality: "local" }),
    P({ id: "research:engine", name: "Research Engine (academic evidence + citation graph)", category: "research", description: "Keyless academic sources (arXiv, Crossref, OpenAlex, Semantic Scholar) + optional web; cross-source dedupe by DOI/title; Semantic Scholar citation edges; LLM claim extraction mapped to evidence ids; contradiction detection; report with reproducibility/limitations; optional persistence to the knowledge fabric. /api/research/academic.", status: "implemented", tags: ["research", "arxiv", "citations", "evidence", "claims"], security_level: "read_only", supported_operations: ["research", "claims", "graph", "persist"], verification_status: "untestable_here" }),
    P({ id: "browser:agent", name: "Browser agent (goal-driven navigation)", category: "browser", description: "LLM-driven navigate/follow/submit/extract loop over an accessibility-style page snapshot. Three engines, best available first: playwright (real chromium, if installed), jsdom (executes the page's own JavaScript in-process — no browser binary; same-origin subresources only, every URL through the SSRF gate), http (static HTML, robots.txt-respecting, cookie jar). JS application shells are detected and, where no engine ran the scripts, reported as needsJs rather than described as content; SSR hydration payloads (Next/Nuxt/Remix/SvelteKit/Angular/JSON-LD) are recovered from the raw markup. The engine actually used is reported by GET /api/browser and in each result. Private networks always denied; form submission needs safe_write confirmation; every step traced.", status: "implemented", tags: ["browser", "web", "navigation", "scraping", "jsdom"], security_level: "safe_write", requires_confirmation: true, supported_operations: ["browse", "extract", "status"], verification_status: "verified" }),
    P({ id: "research:deep", name: "Deep Research (web)", category: "research", description: "Question decomposition → web search (Tavily) → streamed synthesis with citations. Academic evidence lives in research:engine.", status: "implemented", tags: ["research", "search", "citations"], security_level: "read_only", supported_operations: ["research"], verification_status: "verified" }),
    P({ id: "github:intelligence", name: "GitHub Repository Intelligence", category: "github", description: "Repo map (tree/languages/hotspots/key files), LLM architecture brief, diff-grounded PR review with severity findings (optionally posted), issue triage (optionally labelled), and incremental patch → branch → draft PR on existing repos. /api/github/repos/intel. Writes need safe_write confirmation.", status: "implemented", tags: ["github", "review", "triage", "repo-map", "patch"], security_level: "safe_write", requires_confirmation: true, supported_operations: ["map", "analyze", "review", "triage", "patch"], verification_status: "untestable_here" }),
    P({ id: "github:factory", name: "GitHub Coding Factory", category: "github", description: "Generates a project, pushes to a repo, opens CI (Actions), reads logs, reports. Existing-repo work lives in github:intelligence.", status: "implemented", tags: ["github", "ci", "codegen"], security_level: "safe_write", requires_confirmation: true, supported_operations: ["generate", "commit", "ci", "report"], verification_status: "untestable_here" }),
    P({ id: "multimodal:perceive", name: "Multimodal perception (image · document · audio · video · sensor)", category: "media", description: "One typed entry point /api/multimodal: vision via router; document extraction+summary; STT via Groq whisper (free) or STT_URL; sensor series stats/trend/z-score anomalies. Video has four paths, best available first and reported per call as `via`: host ffmpeg (frames + audio track) → ffmpeg compiled to WebAssembly (frame sampling in a worker thread, no host binary — installs from the npm registry) → a video-native model taking the file inline → container metadata read in pure JS. Frame sampling therefore needs no binary on the host; only a vision-capable provider key. Availability reported honestly per modality.", status: "implemented", tags: ["vision", "stt", "document", "video", "sensor", "multimodal", "ffmpeg-wasm"], security_level: "read_only", supported_operations: ["perceive", "status"], verification_status: "verified" }),
    P({ id: "media:studio", name: "Multimodal Studio (generation)", category: "media", description: "Image/audio/video generation via free media providers; vision input in chat; voice mode (STT/TTS).", status: "implemented", tags: ["image", "audio", "video", "vision", "voice"], security_level: "read_only", supported_operations: ["generate", "vision", "tts", "stt"], verification_status: "verified" }),
    P({ id: "automation:workflows", name: "Workflows + Schedules", category: "automation", description: "Agent/transform/branch pipelines, cron schedules with delivery (share/email/webhook) and run history. Event triggers and conditions live in automation:engine.", status: "implemented", tags: ["workflow", "cron", "automation"], security_level: "safe_write", supported_operations: ["run", "schedule", "deliver"], verification_status: "verified" }),
    P({ id: "automation:engine", name: "Automation engine (trigger → condition → agent → verify → action)", category: "automation", description: "Triggers: cron, webhook (secret), device telemetry threshold (edge + cooldown), twin health, job finished, manual. Condition/verify via safe expression DSL or model rubric (PASS/FAIL gate). Actions: webhook, email, remember (memory), twin event, submit job, device actuate (needs physical grant + stored confirmation). Per-stage run log. /api/automations.", status: "implemented", tags: ["automation", "trigger", "workflow", "webhook"], security_level: "safe_write", supported_operations: ["create", "fire", "hook", "runs"], verification_status: "verified" }),
    P({ id: "device:gateway", name: "Physical AI — Device Gateway", category: "device", description: "Per-user device registry with adapters: http (ESP32/Arduino/RPi JSON firmware), mqtt (dependency-free MQTT 3.1.1 client), modbus (Modbus/TCP FC1-6,16) — protocol clients verified against in-repo mocks, UNVERIFIED on real hardware from this sandbox; serial via local bridge (docs/HARDWARE.md); opcua/can NOT AVAILABLE. Telemetry (poll + push ingest), safety loop (limits, interlocks, rate limits, E-stop latch, read-back verification), `physical` grant only via explicit opt-in + per-action confirmation. /api/devices.", status: "partial", tags: ["iot", "esp32", "mqtt", "modbus", "plc", "sensor", "actuator", "safety"], security_level: "physical", requires_confirmation: true, hardware_requirements: ["device", "broker or PLC"], supported_operations: ["register", "read", "ingest", "validate", "actuate", "estop"], verification_status: "verified", locality: "local" }),
    P({ id: "robot:ros2", name: "Robotics — ROS 2 via rosbridge", category: "robot", description: "Dependency-free rosbridge WebSocket client (topics/services/nodes, subscribe/publish/call) + RobotAgent safety governor (velocity clamps, geofence, heartbeat watchdog auto-stop, E-stop latch). Works with real robots or Gazebo/Webots/TurtleBot sims exposing rosbridge. Protocol verified against an in-repo mock; UNVERIFIED on a live ROS 2 graph from this sandbox. /api/robots.", status: "partial", tags: ["robotics", "ros2", "rosbridge", "safety"], security_level: "physical", requires_confirmation: true, hardware_requirements: ["rosbridge_server"], supported_operations: ["inspect", "echo", "govern", "move", "estop"], verification_status: "verified", locality: "local" }),
    P({ id: "twin:digital", name: "Digital Twins", category: "twin", description: "Persisted twins linked to devices: auto-sync from telemetry, history, bounds with critical flags, rule-based forward simulation (safe arithmetic DSL, no eval) to test an actuation before doing it, events, maintenance, health score. Scheduler syncs all twins. /api/twins.", status: "implemented", tags: ["twin", "industrial", "simulation"], security_level: "safe_write", supported_operations: ["create", "sync", "simulate", "health"], verification_status: "verified" }),
    P({ id: "system:observability", name: "Observability & Control Center", category: "system", description: "Structured event log for model/agent/tool/permission/schedule events with a Control Center view, written to a durable SQLite log (node:sqlite, capped at AETHERIS_EVENT_MAX, tail restored on boot) as well as the in-memory ring buffer, so telemetry survives a restart. Secrets are redacted before either copy is written. Missing: cost metadata per call (all providers are free tier) and alerts.", status: "implemented", tags: ["telemetry", "audit", "control-center"], security_level: "admin", supported_operations: ["record", "query", "summary"], verification_status: "verified", locality: "local" }),
    P({ id: "auth:accounts", name: "Accounts & API keys", category: "auth", description: "Google/GitHub/email/phone sign-in, anonymous device identity, personal API keys (sk-aeth-…), OpenAI-compatible /api/v1.", status: "implemented", tags: ["auth", "oauth", "api-keys"], security_level: "admin", supported_operations: ["login", "session", "keys"], verification_status: "verified" }),
    P({ id: "security:guard", name: "Security layer (least privilege, SSRF guard, rate limits, audit)", category: "system", description: "4 permission levels + physical grant (opt-in), single-use confirmation tokens, stop-actions never blocked by dialogs, SSRF/DNS checks on every user-supplied URL (MCP servers, webhooks, browser, http devices), secret redaction in the event buffer, per-IP edge rate limits (shared Upstash counters when configured, in-memory per instance otherwise) + per-uid limits, audit export (/api/telemetry/audit), security headers via middleware, optional login gate (AETHERIS_REQUIRE_LOGIN=1). Honest limits: the limiter fails open when Redis is down; no WAF.", status: "implemented", tags: ["security", "audit", "ssrf", "rate-limit"], security_level: "read_only", supported_operations: ["authorize", "audit", "rate-limit"], verification_status: "verified" }),
    P({ id: "workspace:scopes", name: "Workspaces", category: "system", description: "Named scopes that group knowledge facts, memories, jobs and automations per user; computed stats, default workspace always present. /api/workspaces. Sharing: the owner adds other accounts as editor or viewer (/api/workspaces/:id/members, 25 max, every change audited); members read the shared scope through /api/knowledge?workspace=..., which is resolved by readableScopes() so access is checked in one place. Writes stay the caller\u2019s own data — sharing is read-only, and the default workspace cannot be shared.", status: "implemented", tags: ["workspace", "scope", "sharing"], security_level: "safe_write", supported_operations: ["create", "update", "delete", "stats", "share", "members"], verification_status: "verified", locality: "local" }),
    P({ id: "desktop:app", name: "Desktop app (macOS · Linux · Windows)", category: "system", description: "Native Electron shell in desktop/ around this same application, not a second product. Local-only operation: the default mode runs the server embedded on 127.0.0.1. Local development connects the shell to a separate Next.js process on the same computer (the legacy remote connection setting, validated against /api/health). Public Aetheris hosting is not a supported workflow. Online models and integrations still need internet access. Tray, application menu, aetheris:// deep links, single-instance lock, credential-redacted log, monthly update check. Context-isolated, sandboxed renderer with no Node. Honest limits: unsigned (macOS Gatekeeper / Windows SmartScreen warn) and no self-update — it links the installer. Released on the monthly CalVer cadence.", status: "implemented", tags: ["desktop", "electron", "macos", "linux", "windows", "offline"], security_level: "read_only", supported_operations: ["package", "run", "connect"], verification_status: "verified" }),
    P({ id: "desktop:embedded-server", name: "Embedded desktop server (loopback)", category: "system", description: "This same Next.js app built with AETHERIS_STANDALONE=1 and shipped inside the desktop app as resources/server, started as a child process on 127.0.0.1 under Electron's own Node runtime (ELECTRON_RUN_AS_NODE=1) with a near-empty allow-listed environment. Sets AETHERIS_DESKTOP=1, which turns on the loopback Host allow-list in src/middleware.ts (DNS-rebinding defence) and makes /api/version and /api/health report runtime=desktop. Provider keys are read from <dataDir>/.env.local.", status: process.env.AETHERIS_DESKTOP === "1" ? "implemented" : "not_available", tags: ["desktop", "loopback", "offline", "embedded"], security_level: "read_only", supported_operations: ["serve"], verification_status: "verified", locality: "local" }),
    P({ id: "storage:json", name: "Storage provider (JSON file store)", category: "storage", description: "Single-node JSON collections under data/. Swap point for Postgres/SQLite (StorageProvider interface in src/core/providers).", status: "implemented", tags: ["storage"], security_level: "admin", supported_operations: ["get", "set", "all", "update", "remove"], verification_status: "verified", locality: "local" }),
    P({ id: "system:symbolic-verifier", name: "Neurosymbolic Verification Engine", category: "system", description: "Pure-TypeScript symbolic gate over agent plans. Substitutes a small AST solver, checks unit consistency over SI base and derived units, evaluates per-step guards and global invariants, returns an ACCEPT/REJECT/UNSUPPORTED verdict with a structured reason the agent can recalculate against. No model calls in the loop; deterministic. Sits next to the existing JSON-schema/review/test-loop verification (system:verifier), not on top of it. /api/symbolic.", status: "experimental", tags: ["verify", "symbolic", "math", "units", "physics"], security_level: "safe_write", supported_operations: ["verify", "evaluate", "check-units"], verification_status: "verified", locality: "local" }),
    P({ id: "device:edge", name: "Edge Hardware (ESP32-class bidirectional binding)", category: "device", description: "Typed binding layer to ESP32-class nodes running the http JSON firmware (GET /state, POST /cmd). Discovers devices with tags=['edge'], exposes typed read/write per channel (with units), a bounded local PID-style control loop, and a push-telemetry ingest path. Writes go through the existing device:gateway safety loop — limits, interlocks, rate limits, E-stop, and the `physical` opt-in grant all still apply. No new safety bypass. ESP32 reference sketch in src/core/physical/edge/edge.ts.", status: "experimental", tags: ["esp32", "edge", "iot", "sensor", "actuator", "control-loop"], security_level: "physical", requires_confirmation: true, hardware_requirements: ["esp32 or similar with http JSON firmware"], supported_operations: ["list", "read", "write", "control-loop", "ingest"], verification_status: "untestable_here", locality: "local" }),
    P({ id: "memory:pbnn", name: "Physics-Guided Bayesian Neural Network (PBNN)", category: "memory", description: "Lightweight linear-Gaussian surrogate model with a physics prior on the weights and a soft physics-loss penalty on the data term. Bayesian update is closed-form, so a re-fit is O(d^2 * n) for small d. The agent can use it as a controller, a sanity check on its own reasoning, or a drift detector. Process-local; not a general ML library. /api/learning.", status: "experimental", tags: ["learning", "pbnn", "physics", "drift", "controller"], security_level: "safe_write", supported_operations: ["push", "tick", "predict", "list"], verification_status: "verified", locality: "local" }),
    P({ id: "lab:run", name: "Lab — Sandboxed Self-Modification", category: "execution", description: "Containerised-style environment for the agent to write, compile, test, and deploy a new processing script on the fly. Always goes through the existing execution:server-sandbox (fresh temp workspace, scrubbed env, SIGKILL timeout, output caps, allow-listed binaries, unshare -rn network isolation when available). The optional docker runtime is a strict shell-out to the host `docker` binary, only when the user opted in per request. Required: full_workspace grant + explicit confirmation. Deployed artifacts are written to a copy in the user-configured deploy dir; the host Aetheris process is never modified. /api/lab.", status: "experimental", tags: ["sandbox", "lab", "self-modify", "python", "cpp", "docker"], security_level: "full_workspace", requires_confirmation: true, hardware_requirements: ["docker (optional, for docker runtime only)"], supported_operations: ["run", "compile", "test", "deploy", "list"], verification_status: "verified", locality: "local" }),
    P({ id: "domain:wind-turbine", name: "Wind Turbine Asset Model + Plan Gate", category: "industrial", description: "Typed wind-turbine vocabulary (ChannelId, UNITS, DEFAULT_BOUNDS) and a canonical 2 MW asset (Tower → Nacelle → Rotor → Drivetrain → Thermal → Mechanical → Electrical → Control → Health) wired into the existing Digital Twin simulator. The planAndGate() function pipes a proposed sequence of interventions through (1) the digital-twin simulator, (2) the Neurosymbolic Verifier with SI unit consistency, and (3) an optional PBNN health predictor; it returns a single ACCEPT/REJECT verdict with per-step trajectory, breach list, and learned-model prediction. /api/windturbine. The forward model is first-order linearised (NOT a CFD/FEA simulator); it is for agent reasoning over first-order trade-offs, not for engineering certification.", status: "experimental", tags: ["wind-turbine", "wtg", "digital-twin", "plan-gate", "scada", "industrial", "verifiable"], security_level: "safe_write", supported_operations: ["canon", "plan", "simulate"], verification_status: "verified", locality: "local" }),
    P({ id: "diagnostics:fft", name: "FFT Diagnostics Engine (vibration + bearing signatures)", category: "industrial", description: "Zero-dependency TypeScript FFT (Cooley-Tukey radix-2, iterative bit-reversal) with Hann/Hamming/Blackman/Rectangular windows, coherent-gain-corrected amplitude, magnitude/power/phase spectra, spectral peaks, and a wind-turbine bearing-signature matcher against the canonical outer-race / inner-race / ball-spin / cage frequencies. A higher-level diagnose() function takes a vibration signal + rotor speed and returns severity, peaks, signature matches, and a human-readable summary. The integration layer pipes the digital-twin wind-turbine simulator into the FFT, so /api/diagnostics op:twin takes a twinId and returns a complete diagnostic. Status: experimental; max signal 65536 points; 1D only; not a streaming/overlap-add filter.", status: "experimental", tags: ["fft", "spectrum", "vibration", "diagnostics", "bearing-fault", "wind-turbine"], security_level: "read_only", supported_operations: ["spectrum", "diagnose", "twin"], verification_status: "verified", locality: "local" }),
  ],
};

// ---- User-registered MCP servers (Phase 7) -----------------------------------------------------
const userMcpSource: CapabilitySource = {
  id: "mcp-servers",
  async list() {
    const all = Object.values(await store.all<McpServerRecord>("mcp_servers"));
    return all.flatMap<Capability>((srv) => [
      { id: `mcpserver:${srv.id}`, name: `MCP · ${srv.name}`, category: "connector", provider: "mcp-gateway", description: `${srv.url} · ${srv.manifest?.serverName ?? ""} ${srv.manifest?.serverVersion ?? ""} · ${srv.manifest?.tools.length ?? 0} tools`.trim(), status: srv.health.state === "healthy" ? "implemented" : srv.health.state === "degraded" ? "partial" : "not_available", tags: ["mcp", "user-server", srv.name.toLowerCase()], security_level: "read_only", cost: { unit: "free" }, latency: "fast", reliability: srv.health.calls ? (srv.health.calls - srv.health.failures + 1) / (srv.health.calls + 2) : undefined, supported_operations: ["tools/list", "tools/call", "health"], verification_status: srv.health.lastCheck ? "verified" : "unverified", locality: /localhost|127\.0\.0\.1|192\.168\.|10\./.test(srv.url) ? "local" : "remote", invoke: { kind: "mcp", ref: `/api/mcp/servers/${srv.id}/call` } },
      ...(srv.manifest?.tools ?? []).map<Capability>((t) => ({ id: `mcpserver:${srv.id}.${t.name}`, name: `${srv.name}: ${t.name}`, category: "tool", provider: "mcp-gateway", description: t.description ?? "", status: srv.health.state === "down" ? "not_available" : "implemented", tags: ["mcp", srv.name.toLowerCase(), ...t.name.split(/[_\-.]/)], input_schema: t.inputSchema, security_level: t.permission, requires_confirmation: t.requiresConfirmation, cost: { unit: "free" }, latency: "fast", supported_operations: ["call"], verification_status: "unverified", locality: "remote", invoke: { kind: "mcp", ref: `/api/mcp/servers/${srv.id}/call` } })),
    ]);
  },
};

let booted = false;
/** Register the built-in sources once (idempotent; safe to call from any route). */
export function bootCapabilities() {
  if (booted) return; booted = true;
  registerSource(modelSource); registerSource(agentSource); registerSource(connectorSource); registerSource(platformSource); registerSource(userMcpSource);
  // RAVANA (Aetheris Core #1) registers its own source at import; pull it in here.
  // eslint-disable-next-line @typescript-eslint/no-require-imports -- sync lazy-load: a static import would turn an optional module into a boot-time crash
  try { require("@/aetheris/core/ravana/capabilities"); } catch (e) { console.warn("[aetheris] ravana capabilities load failed", (e as Error).message); }
  loadPlugins();
}
/** Plugins register their own CapabilitySources on import (src/plugins/index.ts). */
// eslint-disable-next-line @typescript-eslint/no-require-imports -- sync lazy-load: plugins are optional, failure must warn, not crash boot
function loadPlugins() { try { require("@/aetheris/plugins"); } catch (e) { console.warn("[aetheris] plugin load failed", (e as Error).message); } }
