import { traced } from "@/aetheris/core/observability/events";
import { commitFilesToBranch, ensureRepo, jobLog, runJobs, waitForRun, type GH } from "@/aetheris/lib/github/api";
import { generateProject, summarizeRun } from "./codegen";
import { workflowYaml } from "./workflow";

export type StepId = "generate" | "repo" | "commit" | "ci" | "logs" | "report";

export type FactoryEvent =
  | { type: "step"; step: StepId; status: "start" | "done" | "error"; detail?: string; data?: Record<string, unknown> }
  | { type: "result"; ok: boolean; conclusion: string; report: string; runUrl?: string; commitUrl?: string; branch: string; files: string[] }
  | { type: "error"; message: string };

export const FACTORY_REPO = process.env.AETHERIS_FACTORY_REPO ?? "aetheris-factory";

export async function runFactory(
  g: GH,
  task: string,
  emit: (e: FactoryEvent) => void,
  opts: { preferred?: string; signal?: AbortSignal; repo?: string; uid?: string } = {},
): Promise<void> {
  return traced({ type: "tool", uid: opts.uid, capability: "github:factory" }, () => runFactoryInner(g, task, emit, opts));
}
async function runFactoryInner(
  g: GH,
  task: string,
  emit: (e: FactoryEvent) => void,
  opts: { preferred?: string; signal?: AbortSignal; repo?: string; uid?: string } = {},
): Promise<void> {
  const step = (step: StepId, status: "start" | "done" | "error", detail?: string, data?: Record<string, unknown>) =>
    emit({ type: "step", step, status, detail, data });

  // 1. Generate code -----------------------------------------------------------------
  step("generate", "start", "Asking the provider mesh to write the project…");
  const { plan, provider, model } = await generateProject(task, opts.preferred);
  step("generate", "done", `${plan.files.length} file(s) · ${plan.language} · via ${provider} (${model})`, {
    files: plan.files.map((f) => f.path),
    summary: plan.summary,
  });

  // 2. Ensure factory repo -------------------------------------------------------------
  const repoName = (opts.repo ?? FACTORY_REPO).replace(/[^\w.-]/g, "").slice(0, 100) || FACTORY_REPO;
  step("repo", "start", `Checking ${g.login}/${repoName}…`);
  const repo = await ensureRepo(g, repoName);
  step("repo", "done", repo.html_url, { url: repo.html_url });

  // 3. Single commit on a run branch -------------------------------------------------
  const runId = `${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 6)}`;
  const branch = `run/${runId}`;
  const dir = `runs/${runId}-${plan.name}`;
  step("commit", "start", `Pushing to ${branch}…`);
  const files = [
    ...plan.files.map((f) => ({ path: `${dir}/${f.path}`, content: f.content })),
    { path: ".github/workflows/aetheris-factory.yml", content: workflowYaml(plan.language, plan.testCommand, dir) },
    { path: `${dir}/AETHERIS.md`, content: `# ${plan.name}\n\n**Task:** ${task}\n\n${plan.summary}\n\nGenerated by Aetheris One via ${provider} (${model}).\n` },
  ];
  const commit = await commitFilesToBranch(g, repoName, repo.default_branch, branch, files, `aetheris: ${task.slice(0, 60)}`);
  step("commit", "done", commit.sha.slice(0, 7), { url: commit.url, branch });

  // 4. Wait for GitHub Actions ---------------------------------------------------------
  step("ci", "start", "Waiting for GitHub Actions to pick up the run…");
  const run = await waitForRun(g, repoName, commit.sha, {
    signal: opts.signal,
    onUpdate: (r) => {
      if (r) step("ci", "start", `Workflow ${r.status.replace("_", " ")}…`, { url: r.html_url });
    },
  });
  const conclusion = run.conclusion ?? "unknown";
  step("ci", conclusion === "success" ? "done" : "error", `Run ${conclusion}`, { url: run.html_url });

  // 5. Read logs -------------------------------------------------------------------------
  step("logs", "start", "Reading CI logs…");
  const jobs = await runJobs(g, repoName, run.id);
  let log = "";
  for (const j of jobs) {
    try {
      log += `=== job: ${j.name} (${j.conclusion}) ===\n` + (await jobLog(g, repoName, j.id)) + "\n";
    } catch (e) {
      log += `(could not fetch log for ${j.name}: ${(e as Error).message})\n`;
    }
  }
  // Strip timestamps GitHub prefixes on every line.
  log = log.replace(/^\d{4}-\d{2}-\d{2}T[\d:.]+Z /gm, "");
  step("logs", "done", `${log.split("\n").length} lines`);

  // 6. Summarise ---------------------------------------------------------------------------
  step("report", "start", "Summarising…");
  let report: string;
  try {
    report = await summarizeRun({ task, plan, conclusion, log, preferred: opts.preferred });
  } catch (e) {
    report = `CI finished with **${conclusion}**. (Summary unavailable: ${(e as Error).message})\n\n\`\`\`\n${log.slice(-3000)}\n\`\`\``;
  }
  step("report", "done");

  emit({
    type: "result",
    ok: conclusion === "success",
    conclusion,
    report,
    runUrl: run.html_url,
    commitUrl: commit.url,
    branch,
    files: plan.files.map((f) => `${dir}/${f.path}`),
  });
}
