import type { SeedTuple } from "./types";

export const business: SeedTuple[] = [
  ["Go-to-market one-pager", "Positioning, channels, budget in ₹, KPIs.", "@strategist @marketer One-page GTM for {{product}} targeting {{audience}} in India. Include positioning, 3 channels with weekly budget in ₹, launch-week timeline and 5 measurable KPIs.", ["strategist", "marketer"], ["business", "startup", "marketing"]],
  ["PRD from a feature idea", "Problem → requirements → metrics.", "@product Write a PRD for: {{feature}}. Sections: problem & evidence, goals/non-goals, users, requirements (must/should/could), UX notes, success metrics, risks, open questions. Add 5 user stories with Given/When/Then.", ["product"], ["business", "product"]],
  ["RICE prioritisation", "Score and rank the backlog.", "@product Here is my backlog. Score each item with RICE (state assumptions for reach and effort), rank them, and explain the top 3 and bottom 3 in one line each.\n\n{{backlog}}", ["product"], ["business", "product", "prioritisation"]],
  ["Unit economics", "CAC, LTV, payback, margin.", "@founder Compute unit economics for {{business}}: price {{price}}, gross margin {{gm}}, CAC {{cac}}, monthly churn {{churn}}. Show LTV, LTV/CAC, payback months, and what must change to reach LTV/CAC ≥ 3.", ["founder"], ["business", "startup", "finance"]],
  ["Investor pitch deck outline", "10 slides with speaker notes.", "@founder @presentation Create a 10-slide seed pitch deck for {{startup}}: title, problem, solution, why now, market, product, traction, business model, team, ask. For each: action title, visual, 3 bullets, speaker notes.", ["founder", "presentation"], ["business", "startup", "pitch"]],
  ["Competitor teardown", "Positioning, pricing, weaknesses.", "@strategist Tear down these competitors for {{category}}: {{competitors}}. Table: positioning, pricing, target segment, strengths, weaknesses, and where we can win. End with a 2×2 positioning map described in words.", ["strategist"], ["business", "strategy"]],
  ["SOP writer", "Numbered steps with checks.", "@ops Write an SOP for {{process}}: purpose, scope, roles, numbered steps with checkpoints, exceptions, KPIs, and a one-page checklist version.", ["ops"], ["business", "operations"]],
  ["Job description", "Outcomes-based, inclusive.", "@hr Write a job description for {{role}} at {{company}}: mission of the role, outcomes in the first 90 days, must-haves (≤5), nice-to-haves, how we work, compensation range in ₹ LPA, inclusive language.", ["hr"], ["business", "hiring"]],
  ["Structured interview kit", "Questions + scoring rubric.", "@hr @interview Create a structured interview kit for {{role}}: 6 behavioural questions mapped to competencies, 3 role-specific exercises, a 1–4 scoring rubric per competency, and red flags.", ["hr", "interview"], ["business", "hiring"]],
  ["Negotiation prep sheet", "BATNA, anchors, concessions.", "@negotiator Prepare me for negotiating {{deal}}. Fill a prep sheet: my goals, my BATNA and theirs, reservation price, opening anchor with justification, concessions ranked, likely objections with responses, and a word-for-word opening.", ["negotiator"], ["business", "negotiation"]],
  ["Weekly business review", "Metrics narrative + decisions.", "@strategist @notes Turn these metrics into a weekly business review: what moved and why, 3 insights, 3 decisions needed, risks, and next week's focus. Keep it to one page.\n\n{{metrics}}", ["strategist", "notes"], ["business", "analytics"]],
  ["Pricing strategy", "Tiers, anchors, willingness to pay.", "@strategist Design pricing for {{product}} for {{market}}: value metric, 3 tiers with anchoring, feature fences, annual discount, and a plan to test willingness-to-pay. Compare to 3 competitors' pricing.", ["strategist"], ["business", "pricing"]],
  ["Cold outreach sequence", "5 touches that get replies.", "@sales Write a 5-touch outbound sequence (email, LinkedIn, email, call script, break-up email) to {{persona}} about {{offer}}. Personalisation hooks, ≤90 words per email, one clear ask.", ["sales"], ["business", "sales"]],
  ["Customer discovery script", "Non-leading interview questions.", "@ux-research @product Write a 30-minute customer discovery interview script for {{hypothesis}}: screener, warm-up, past-behaviour questions (non-leading), problem depth probes, closing. Then a synthesis template.", ["ux-research", "product"], ["business", "research", "product"]],
  ["OKRs for a quarter", "Objectives with measurable KRs.", "@strategist Draft OKRs for {{team}} next quarter given our strategy: {{strategy}}. 3 objectives, 3 KRs each (measurable, with baseline and target), and initiatives mapped to each KR.", ["strategist"], ["business", "planning"]],
  ["Vendor comparison matrix", "Weighted decision matrix.", "@decision Compare vendors {{vendors}} for {{need}}. Elicit criteria with weights (sum 100), score 1–5, show weighted totals, run a pre-mortem on the winner, and state what would change the decision.", ["decision"], ["business", "procurement", "decision"]],
  ["Board update email", "Concise, honest, forward-looking.", "@email @founder Draft a monthly investor/board update: highlights, lowlights, key metrics vs plan, cash & runway, asks, next month. Honest tone, ≤400 words.\n\nData:\n{{data}}", ["email", "founder"], ["business", "startup", "communication"]],
  ["Brand positioning statement", "For/is/that/because.", "@brand Write a positioning statement for {{brand}}: for [audience], [brand] is the [category] that [differentiator] because [reason to believe]. Then 5 taglines (≤6 words) and a do/don't brand voice table.", ["brand"], ["business", "branding"]],
  ["Business plan (bank-ready)", "Sections lenders expect.", "@founder @accountant Write a bank-ready business plan for {{business}} in India: summary, market, operations, team, 3-year P&L projection table (assumptions stated), funding requirement and repayment plan, risks.", ["founder", "accountant"], ["business", "finance", "planning"]],
  ["Franchise / expansion evaluation", "Go / no-go with numbers.", "@strategist @accountant Evaluate expanding {{business}} to {{city}}: demand signals, competition, unit economics for one outlet (capex, opex, break-even months), risks, and a go/no-go recommendation.", ["strategist", "accountant"], ["business", "expansion"]],
];
