import type { SeedTuple } from "./types";

export const education: SeedTuple[] = [
  ["7-day exam crash course", "Syllabus → daily plan with quizzes and strict grading.", "@exam I have an exam on {{subject}} in 7 days and can study {{hours}} hours a day. Build a day-by-day plan with 25-minute blocks, rank topics by weightage × my weakness ({{weak topics}}), end each day with a 5-question quiz and grade my answers strictly.", ["exam"], ["education", "students", "exam"]],
  ["Feynman technique coach", "Explain it back until it's truly simple.", "@tutor I want to learn {{concept}} using the Feynman technique. Ask me to explain it in my own words, find the gaps, explain the gap simply, then have me try again. Repeat until I can teach it to a 12-year-old.", ["tutor"], ["education", "learning"]],
  ["Spaced repetition deck", "Turn notes into Anki-style cards.", "@tutor Convert these notes into 20 spaced-repetition flashcards (question on front, concise answer on back, one fact per card, cloze deletions where useful). Add 3 'why' cards that test understanding, not recall.\n\n{{notes}}", ["tutor"], ["education", "flashcards"]],
  ["Physics numericals drill", "Ten graded problems with full solutions.", "@physics Give me 10 numerical problems on {{topic}} graded easy→hard (JEE Main level). Show full solutions after a divider, with units and a sanity check for each.", ["physics"], ["education", "physics", "jee"]],
  ["Organic mechanism walkthrough", "Step-by-step electron pushing.", "@chemistry Walk me through the mechanism of {{reaction}} step by step: nucleophile, electrophile, intermediates, rate-determining step, stereochemistry. Then give 3 variations that examiners like to ask.", ["chemistry"], ["education", "chemistry"]],
  ["NEET biology chapter map", "Concept map + high-yield facts.", "@biology Create a concept map (as an indented outline) for NCERT chapter '{{chapter}}', then list 25 high-yield one-line facts NEET repeatedly tests, then 10 assertion-reason questions with answers.", ["biology"], ["education", "biology", "neet"]],
  ["UPSC answer writing", "Structured 250-word answer with critique.", "@history Write a 250-word UPSC Mains answer to: '{{question}}'. Use intro–body (thematic sub-headings)–conclusion, add 2 dates and 1 scholar's view. Then critique your own answer against the UPSC marking scheme.", ["history"], ["education", "upsc", "writing"]],
  ["Economics diagram explainer", "Describe the graph precisely.", "@economics Explain {{model}} with the diagram described precisely (axes, curves, shifts, new equilibrium) and a real Indian example with the year. Then give 3 MCQs that test the diagram.", ["economics"], ["education", "economics"]],
  ["Maths proof tutor", "Proof with the reasoning made explicit.", "@math Prove: {{statement}}. Before the proof, state the strategy (direct, contradiction, induction…) and why. After the proof, list the two places students usually go wrong.", ["math"], ["education", "maths"]],
  ["Mock viva", "Oral exam with follow-ups.", "@tutor Conduct a mock viva on {{topic}}. Ask one question at a time, follow up on weak answers like a real examiner, and after 8 questions give me a score out of 10 with what to revise.", ["tutor"], ["education", "viva"]],
  ["Explain like I'm 8", "Kid-friendly with a home experiment.", "@kids Explain {{topic}} to an 8-year-old with a story, one analogy from home, and a safe 5-minute experiment we can do in the kitchen.", ["kids"], ["education", "kids"]],
  ["Geography case study", "Process → place → people.", "@geography Build a case study on {{phenomenon}} in {{place}}: physical process, why it happens there, impact on people and economy, and management strategies. Include a sketch-map description.", ["geography"], ["education", "geography"]],
  ["Lesson plan for teachers", "45-minute plan with activities.", "@tutor Create a 45-minute lesson plan for {{grade}} on {{topic}}: learning objectives (Bloom's), hook (5 min), direct instruction (15), activity (15), exit ticket (10), differentiation for fast and slow learners.", ["tutor"], ["education", "teachers"]],
  ["Past-paper pattern analysis", "Find what's actually asked.", "@exam Here are the topics of the last {{n}} years' questions for {{exam}}. Find the repeating patterns, predict the 10 most likely topics this year with reasons, and tell me what to skip.\n\n{{topics list}}", ["exam"], ["education", "exam"]],
  ["Philosophy seminar", "Steelman two positions.", "@philosopher Run a seminar on '{{question}}'. Define terms, steelman two opposing positions with their best arguments, then ask me three Socratic questions to sharpen my own view.", ["philosopher"], ["education", "philosophy"]],
  ["Study-abroad SOP draft", "Specific, cliché-free SOP.", "@scholarship Draft a 700-word SOP for {{programme}} at {{university}}. My background: {{background}}. Make it specific (projects, numbers, why this programme/professor), no clichés, and end with a 2-line career goal.", ["scholarship"], ["education", "study-abroad"]],
  ["Concept in Tamil", "தமிழில் விளக்கம்.", "@tamil {{concept}} என்பதை எளிய தமிழில், ஒரு அன்றாட உதாரணத்துடன் விளக்கு. முடிவில் 3 சுய-சோதனைக் கேள்விகள் கொடு.", ["tamil"], ["education", "tamil"]],
  ["Concept in Hindi", "हिंदी में व्याख्या.", "@hindi {{concept}} को आसान हिंदी में एक रोज़मर्रा के उदाहरण के साथ समझाओ। अंत में 3 स्व-परीक्षण प्रश्न दो।", ["hindi"], ["education", "hindi"]],
  ["Statistics for a thesis", "Which test and why.", "@statistician My thesis data: {{describe variables, sample size, design}}. Which statistical tests should I use and why? Check assumptions, give the exact R/Python code, and tell me how to report results in APA style.", ["statistician"], ["education", "statistics", "research"]],
  ["Literature review skeleton", "Themes, gaps, citations plan.", "@scholar Build a literature review skeleton on {{topic}}: 5 themes with 2–3 seminal works each (author, year), the debates between them, the gap my work could fill, and a citation-management plan.", ["scholar"], ["education", "research", "academic"]],
];
