import type { SeedTuple } from "./types";

export const marketing: SeedTuple[] = [
  ["Landing page copy", "Hero → benefits → proof → CTA.", "@copywriter Write landing page copy for {{product}} for {{audience}}: hero headline (3 variants), sub-headline, 3 benefit blocks, social proof section, objection-handling FAQ (5), CTA copy. Benefit-led, no jargon.", ["copywriter"], ["marketing", "copywriting"]],
  ["Content calendar (4 weeks)", "Platform-native posts with hooks.", "@social Build a 4-week content calendar for {{brand}} on {{platforms}}. Table: day, platform, format, hook, CTA, metric. Mix education/story/proof/offer 40/30/20/10.", ["social"], ["marketing", "social-media"]],
  ["SEO content brief", "Intent, outline, entities, schema.", "@seo Create an SEO brief for the keyword '{{keyword}}': search intent, SERP analysis, title (≤60), H2/H3 outline, entities to cover, internal links, FAQ schema questions, target word count.", ["seo"], ["marketing", "seo", "content"]],
  ["Email welcome sequence", "5 emails over 10 days.", "@copywriter Write a 5-email welcome sequence for {{product}}: day 0 welcome, day 2 quick win, day 4 story/proof, day 7 objection, day 10 offer. Subject lines ×3 each, ≤150 words per email.", ["copywriter"], ["marketing", "email"]],
  ["Ad copy variants", "Google + Meta, tested angles.", "@copywriter Write ad copy for {{offer}}: 5 Google RSA headlines + 3 descriptions, 3 Meta primary texts (angles: pain, gain, proof) with headline and CTA, and which to test first.", ["copywriter"], ["marketing", "ads"]],
  ["LinkedIn thought-leadership", "5 posts from one insight.", "@social @linkedin Turn this insight into 5 LinkedIn posts with different formats (story, listicle, contrarian, how-to, question). Strong first line, line breaks, no hashtags spam.\n\nInsight: {{insight}}", ["social", "linkedin"], ["marketing", "linkedin"]],
  ["Reel script (30s)", "Hook by second 3.", "@screenwriter @social Write a 30-second reel script about {{topic}}: hook (≤3s), 3 beats with on-screen text, CTA, and 3 caption options. Note the visuals per beat.", ["screenwriter", "social"], ["marketing", "video", "reels"]],
  ["Product launch plan", "Pre-launch → launch → post.", "@marketer Plan the launch of {{product}} over 6 weeks: pre-launch (waitlist, teasers), launch day (channels, assets, PR), post-launch (case studies, referrals). Table with owners, dates, KPIs.", ["marketer"], ["marketing", "launch"]],
  ["Press release", "Standard structure, quotable.", "@journalist Write a press release announcing {{news}} from {{company}}: headline, sub-head, dateline, lede, 2 quotes, details, boilerplate, media contact. AP style.", ["journalist"], ["marketing", "pr"]],
  ["Naming brainstorm", "50 names in 5 themes.", "@brand Generate 50 brand names for {{product}} in 5 themes (descriptive, evocative, coined, compound, acronym). Mark the 10 best with rationale and note domain/trademark caveats.", ["brand"], ["marketing", "branding", "naming"]],
  ["Customer persona", "Evidence-based, not fluffy.", "@marketer @ux-research Build 2 customer personas for {{product}} from this data: goals, pains, triggers, objections, channels, a day in the life, and messaging that resonates.\n\n{{data}}", ["marketer", "ux-research"], ["marketing", "personas"]],
  ["Referral programme design", "Incentives and mechanics.", "@marketer Design a referral programme for {{product}}: incentive for referrer and referee, mechanics, fraud controls, viral coefficient assumptions, and copy for the invite message.", ["marketer"], ["marketing", "growth"]],
  ["YouTube video plan", "Title, thumbnail, script outline.", "@screenwriter @seo Plan a YouTube video on {{topic}}: 5 title options, thumbnail concept, hook script, chaptered outline with timings, CTA, description with keywords.", ["screenwriter", "seo"], ["marketing", "youtube"]],
  ["WhatsApp broadcast", "Short, personal, compliant.", "@copywriter Write 3 WhatsApp broadcast messages for {{offer}} to {{audience}} in India: ≤60 words, personal tone, one CTA, opt-out line. One in English, one in Hinglish, one in Tamil.", ["copywriter"], ["marketing", "whatsapp", "india"]],
  ["Case study", "Problem → solution → results.", "@copywriter Write a customer case study from these notes: headline with the result, context, challenge, solution, results with numbers, quote, CTA. 600 words.\n\n{{notes}}", ["copywriter"], ["marketing", "content"]],
  ["Marketing budget allocation", "Channels vs stage.", "@marketer We have ₹{{budget}}/month for {{product}} at {{stage}}. Allocate across channels with expected CAC ranges, a 90-day test plan and kill criteria per channel.", ["marketer"], ["marketing", "budget"]],
  ["App store listing", "ASO title, subtitle, description.", "@seo @copywriter Write an App Store / Play Store listing for {{app}}: title (≤30), subtitle, short description, long description with keywords, 5 screenshot captions, what's-new text.", ["seo", "copywriter"], ["marketing", "aso", "mobile"]],
  ["Webinar plan", "Topic, promo, run-of-show.", "@marketer Plan a 45-minute webinar on {{topic}}: promise, 3 promo emails, run-of-show with timings, poll questions, offer at the end, follow-up sequence.", ["marketer"], ["marketing", "events"]],
];
