import type { SeedTuple } from "./types";

/** Security & privacy for everyone, plus emergency preparedness. */
export const safety: SeedTuple[] = [
  ["Personal security audit", "30-minute lockdown.", "@security Walk me through a 30-minute personal security audit: password manager, 2FA on the 10 accounts that matter, SIM/UPI protections, phone settings, recovery emails, breach check, and a monthly 5-minute routine.", ["security"], ["safety", "security", "personal"]],
  ["Is this a scam?", "Analyse a message or call.", "@security @consumer I received this: {{message}}. Tell me if it's likely a scam, the red flags, what the scammer wants, what to do now (and NOT do), and how to report it in India (1930, cybercrime.gov.in).", ["security", "consumer"], ["safety", "scam", "india"]],
  ["UPI / bank fraud response", "First 60 minutes.", "@consumer @security Money left my account via {{method}} at {{time}}. Give me a minute-by-minute action plan: bank helpline, 1930, freezing, evidence, complaint format, and chances of recovery. Then how to prevent it.", ["consumer", "security"], ["safety", "fraud", "upi", "india"]],
  ["Phishing awareness training", "For staff or family.", "@security @tutor Create a 20-minute phishing awareness session for {{audience}}: 6 real-style examples with the tells, a decision checklist, what to do if clicked, and a 10-question quiz.", ["security", "tutor"], ["safety", "phishing", "training"]],
  ["Secure my small business", "Practical, ₹-conscious.", "@security @ops My {{business}} has {{staff}} staff, uses {{tools}}. Give a prioritised security plan: accounts and MFA, device hygiene, backups (3-2-1), access control, vendor/UPI fraud controls, incident contacts, and a policy one-pager.", ["security", "ops"], ["safety", "security", "small-business"]],
  ["Privacy settings walkthrough", "Phone, browser, social.", "@security Give step-by-step privacy hardening for {{device}} and {{apps}}: permissions, ad tracking, location history, DMs, public profile exposure, and backups. Explain the trade-off of each setting.", ["security"], ["safety", "privacy"]],
  ["Digital footprint cleanup", "Reduce what's public about me.", "@security @researcher Help me audit and shrink my online footprint: search queries to run on myself, data-broker removal, old accounts to delete, photo metadata, and a template request under DPDP for data erasure.", ["security", "researcher"], ["safety", "privacy", "footprint"]],
  ["Child online safety plan", "Age-based rules and settings.", "@parenting @security For my {{age}}-year-old on {{devices}}: parental controls, app allow-lists, chat and gaming safety, grooming warning signs, a family tech agreement, and how to talk about it without fear.", ["parenting", "security"], ["safety", "kids", "online-safety"]],
  ["Secure a home Wi-Fi & IoT", "Router to smart bulbs.", "@security @embedded Harden my home network: router settings (WPA3, guest network, firmware), IoT isolation, camera privacy, DNS filtering, and a checklist for each new device.", ["security", "embedded"], ["safety", "home-network", "iot"]],
  ["Travel safety brief", "Destination-specific.", "@travel @security Safety brief for {{destination}} for a {{traveller}}: common scams, areas/times to avoid, transport safety, health risks, emergency numbers, embassy details, document backups, and a check-in protocol.", ["travel", "security"], ["safety", "travel"]],
  ["Women's safety plan", "Practical, not paranoid.", "@security @mental I'm a woman {{situation}} (commuting late / new city / solo travel). Give practical safety measures, apps and features (SOS, location sharing), scripts for uncomfortable situations, legal rights in India, and helplines (181, 112).", ["security", "mental"], ["safety", "women", "india"]],
  ["Emergency go-bag & family plan", "Floods, cyclones, quakes.", "@planner @health We live in {{city}} ({{risks}}). Build a family emergency plan: go-bag list, documents kit, meeting points, communication tree, 72-hour supplies, elderly/pet needs, and a seasonal review.", ["planner", "health"], ["safety", "emergency", "preparedness"]],
  ["Flood / cyclone checklist", "Before, during, after.", "@environment @health A {{event}} warning is issued for {{city}}. Give before/during/after checklists: home prep, power/gas, drinking water, evacuation triggers, official sources, and post-event health precautions.", ["environment", "health"], ["safety", "disaster", "india"]],
  ["Fire safety at home/office", "Prevention and escape.", "@homeimprove @health Fire-safety plan for a {{space}}: hazards to fix, extinguisher types and placement, smoke alarms, escape routes and drill, kitchen/electrical rules, and what to do in the first 2 minutes.", ["homeimprove", "health"], ["safety", "fire"]],
  ["Road safety for a new rider/driver", "Habits that save lives.", "@health @tutor I just started {{riding_or_driving}} in {{city}}. Give me the 20 habits that matter most, night/rain rules, defensive techniques, helmet/seatbelt facts, and what to do after an accident (legal + medical).", ["health", "tutor"], ["safety", "road-safety", "india"]],
  ["Workplace safety induction", "Site-specific briefing.", "@ops @security Write a safety induction for new workers at a {{site}}: hazards, PPE, permits, emergency procedures, reporting, do's/don'ts, and a 10-question comprehension check. Simple language, translatable.", ["ops", "security"], ["safety", "workplace", "induction"]],
  ["Password & account recovery plan", "Before you're locked out.", "@security Set up my recovery plan: which accounts are 'root' (email, phone, bank), recovery codes storage, trusted contacts, what to do if my phone is lost/stolen (step-by-step), and a printed emergency card.", ["security"], ["safety", "accounts", "recovery"]],
  ["Secure code review checklist", "OWASP-aligned, by language.", "@security @reviewer Give a secure code review checklist for {{language}}/{{framework}}: input validation, auth/session, secrets, injection, deserialisation, dependencies, logging, and 5 grep patterns that find common bugs fast.", ["security", "reviewer"], ["safety", "appsec", "code-review"]],
  ["Threat model my app", "STRIDE in an hour.", "@security @architect Threat-model {{app}}: assets, entry points, trust boundaries, STRIDE per component, top 10 threats ranked, mitigations, and what to log/alert on.", ["security", "architect"], ["safety", "threat-model", "appsec"]],
  ["Respond to a ransomware/hack", "Small org playbook.", "@security @sre We think we've been hacked: {{signs}}. Give the first-24-hours playbook: isolate, preserve evidence, communications, backups restore order, regulator/CERT-In reporting, and lessons-learned template.", ["security", "sre"], ["safety", "incident-response"]],
  ["Elderly-proof against scams", "Teach my parents.", "@security @parenting Create a simple guide for my {{age}}-year-old parents: 8 common scams (digital arrest, KYC, lottery, OTP), the one rule for each, a fridge-magnet checklist, and a script for me to teach it kindly.", ["security", "parenting"], ["safety", "scam", "elders", "india"]],
  ["மோசடி எச்சரிக்கை (தமிழ்)", "Tamil scam-awareness guide.", "@security @tamil தமிழில் ஒரு எளிய மோசடி விழிப்புணர்வு வழிகாட்டி: 8 பொதுவான மோசடிகள் (OTP, KYC, டிஜிட்டல் அரெஸ்ட், லாட்டரி), அடையாளம் காணும் அறிகுறிகள், செய்யக்கூடாதவை, மற்றும் 1930 / cybercrime.gov.in இல் புகார் செய்யும் முறை.", ["security", "tamil"], ["safety", "tamil", "scam"]],
  ["साइबर सुरक्षा (हिंदी)", "Hindi safety guide.", "@security @hindi हिंदी में एक आसान साइबर सुरक्षा गाइड: 8 आम ठगी (OTP, KYC, डिजिटल अरेस्ट, लॉटरी), पहचानने के संकेत, क्या न करें, और 1930 / cybercrime.gov.in पर शिकायत कैसे करें।", ["security", "hindi"], ["safety", "hindi", "scam"]],
];
