import type { SeedTuple } from "./types";

/**
 * Writing recipes in the world's major languages — each prompt is written natively so speakers
 * get a first-class experience, not a translated English prompt. Tagged by language for filtering.
 */
export const world: SeedTuple[] = [
  // ── Universal ────────────────────────────────────────────────────────────────
  ["Write in any language", "Native-quality writing, your language.", "@writer @polyglot Write a {{type}} about {{topic}} in {{language}}, for {{audience}}. Native idiom and register (not translated English), culturally appropriate examples, {{length}}. Then list 3 phrases a learner might find tricky.", ["writer", "polyglot"], ["world", "multilingual", "writing"]],
  ["Same message, 10 languages", "Localise a short text everywhere.", "@translator Localise this text into English, Spanish, French, German, Portuguese, Arabic, Hindi, Chinese (Simplified), Japanese and Indonesian. Adapt idioms and formality per culture; keep placeholders. Return a table with a back-translation column.\n\n{{text}}", ["translator"], ["world", "multilingual", "localisation"]],
  ["Bilingual article", "Side-by-side, same meaning.", "@writer @translator Write a 500-word article on {{topic}} in {{language_a}} and {{language_b}} with matching paragraphs (not literal translation — each should read natively). Add a glossary of 10 key terms in both.", ["writer", "translator"], ["world", "multilingual", "bilingual"]],
  ["Detect & reply in my language", "Auto-language conversation.", "@polyglot Reply in whatever language I write in, matching my register. If my text mixes languages (Hinglish, Tanglish, Spanglish), reply the same way. Start: {{message}}", ["polyglot"], ["world", "multilingual", "conversation"]],
  ["Transliterate & romanise", "Any script → Latin, with pronunciation.", "@polyglot Transliterate this text into the Latin alphabet using the standard scheme for the language (ISO 15919, Pinyin, Hepburn, etc.), then give a simple 'how to say it' version for English speakers, and a line-by-line translation.\n\n{{text}}", ["polyglot"], ["world", "multilingual", "transliteration"]],
  ["Cultural adaptation check", "Will this land in another market?", "@brand @translator This copy is for {{market}}: {{copy}}. Check names, colours, idioms, humour, dates/numbers, imagery and legal/cultural sensitivities; propose an adapted version and explain each change.", ["brand", "translator"], ["world", "multilingual", "localisation", "marketing"]],

  // ── Indian languages ─────────────────────────────────────────────────────────
  ["தமிழ் — கட்டுரை/வலைப்பதிவு", "Tamil article or blog.", "@tamil @writer '{{topic}}' பற்றி {{audience}} படிக்கும்படி {{words}} சொற்களில் தமிழில் ஒரு {{type}} (கட்டுரை/வலைப்பதிவு/உரை) எழுது. இயல்பான தமிழ், தேவையற்ற ஆங்கிலக் கலப்பு இன்றி, தலைப்புகள் மற்றும் ஒரு சுருக்கத்துடன்.", ["tamil", "writer"], ["world", "tamil", "writing"]],
  ["தமிழ் — அலுவலகக் கடிதம்", "Tamil formal letter.", "@tamil {{recipient}}க்கு {{purpose}} குறித்து தமிழில் முறையான கடிதம் எழுது: சரியான வடிவம் (முகவரி, நாள், பொருள், விளி, முடிவு), தெளிவான கோரிக்கை, மரியாதையான தொனி. பின்னர் ஒரு சுருக்கமான WhatsApp பதிப்பும்.", ["tamil"], ["world", "tamil", "letter"]],
  ["हिंदी — लेख/ब्लॉग", "Hindi article or blog.", "@hindi @writer '{{topic}}' पर {{audience}} के लिए {{words}} शब्दों का हिंदी {{type}} (लेख/ब्लॉग/भाषण) लिखो। सहज हिंदी, उपशीर्षक, एक उदाहरण प्रति भाग, और अंत में 3 पंक्तियों का सार।", ["hindi", "writer"], ["world", "hindi", "writing"]],
  ["हिंदी — सोशल मीडिया कैप्शन", "Hindi captions and hooks.", "@hindi @social {{brand_or_topic}} के लिए 10 हिंदी कैप्शन लिखो ({{platform}}): 3 भावनात्मक, 3 मज़ेदार, 2 जानकारीपूर्ण, 2 सवाल वाले; हर एक के साथ हैशटैग और एक हुक लाइन।", ["hindi", "social"], ["world", "hindi", "social"]],
  ["বাংলা — প্রবন্ধ", "Bengali essay/article.", "@polyglot @writer '{{topic}}' বিষয়ে {{audience}}-এর জন্য {{words}} শব্দের একটি বাংলা {{type}} লিখুন। স্বাভাবিক, প্রাঞ্জল বাংলা; উপশিরোনাম; প্রতিটি অংশে একটি বাস্তব উদাহরণ; শেষে তিন লাইনের সারসংক্ষেপ।", ["polyglot", "writer"], ["world", "bengali", "bangla", "writing"]],
  ["తెలుగు — వ్యాసం", "Telugu article.", "@polyglot @writer '{{topic}}' గురించి {{audience}} కోసం {{words}} పదాల తెలుగు {{type}} రాయండి. సహజమైన తెలుగు, ఉపశీర్షికలు, ప్రతి భాగంలో ఒక ఉదాహరణ, చివర్లో మూడు వాక్యాల సారాంశం.", ["polyglot", "writer"], ["world", "telugu", "writing"]],
  ["ಕನ್ನಡ — ಲೇಖನ", "Kannada article.", "@polyglot @writer '{{topic}}' ಕುರಿತು {{audience}} ಗಾಗಿ {{words}} ಪದಗಳ ಕನ್ನಡ {{type}} ಬರೆಯಿರಿ. ಸಹಜ ಕನ್ನಡ, ಉಪಶೀರ್ಷಿಕೆಗಳು, ಪ್ರತಿ ಭಾಗದಲ್ಲಿ ಒಂದು ಉದಾಹರಣೆ, ಕೊನೆಯಲ್ಲಿ ಮೂರು ಸಾಲಿನ ಸಾರಾಂಶ.", ["polyglot", "writer"], ["world", "kannada", "writing"]],
  ["മലയാളം — ലേഖനം", "Malayalam article.", "@polyglot @writer '{{topic}}' എന്ന വിഷയത്തിൽ {{audience}}-നു വേണ്ടി {{words}} വാക്കുകളുള്ള മലയാളം {{type}} എഴുതുക. സ്വാഭാവിക മലയാളം, ഉപശീർഷകങ്ങൾ, ഓരോ ഭാഗത്തിലും ഒരു ഉദാഹരണം, അവസാനം മൂന്നു വരി സംഗ്രഹം.", ["polyglot", "writer"], ["world", "malayalam", "writing"]],
  ["मराठी — लेख", "Marathi article.", "@polyglot @writer '{{topic}}' या विषयावर {{audience}} साठी {{words}} शब्दांचा मराठी {{type}} लिहा. सहज मराठी, उपशीर्षके, प्रत्येक भागात एक उदाहरण, शेवटी तीन ओळींचा सारांश.", ["polyglot", "writer"], ["world", "marathi", "writing"]],
  ["ગુજરાતી — લેખ", "Gujarati article.", "@polyglot @writer '{{topic}}' વિશે {{audience}} માટે {{words}} શબ્દોનો ગુજરાતી {{type}} લખો. સહજ ગુજરાતી, ઉપશીર્ષકો, દરેક ભાગમાં એક ઉદાહરણ, અંતે ત્રણ લીટીનો સાર.", ["polyglot", "writer"], ["world", "gujarati", "writing"]],
  ["ਪੰਜਾਬੀ — ਲੇਖ", "Punjabi article.", "@polyglot @writer '{{topic}}' ਬਾਰੇ {{audience}} ਲਈ {{words}} ਸ਼ਬਦਾਂ ਦਾ ਪੰਜਾਬੀ {{type}} ਲਿਖੋ। ਸੁਭਾਵਿਕ ਪੰਜਾਬੀ, ਉਪ-ਸਿਰਲੇਖ, ਹਰ ਹਿੱਸੇ ਵਿੱਚ ਇੱਕ ਉਦਾਹਰਨ, ਅੰਤ ਵਿੱਚ ਤਿੰਨ ਸਤਰਾਂ ਦਾ ਸਾਰ।", ["polyglot", "writer"], ["world", "punjabi", "writing"]],
  ["اردو — مضمون", "Urdu essay/article.", "@polyglot @writer '{{topic}}' پر {{audience}} کے لیے {{words}} الفاظ کا اردو {{type}} لکھیں۔ رواں اور شستہ اردو، ذیلی عنوانات، ہر حصے میں ایک مثال، آخر میں تین سطری خلاصہ۔", ["polyglot", "writer"], ["world", "urdu", "writing"]],
  ["ଓଡ଼ିଆ / অসমীয়া — ଲେଖା", "Odia or Assamese article.", "@polyglot @writer Write a {{words}}-word {{type}} on {{topic}} in {{language}} (Odia or Assamese) for {{audience}}: natural register, sub-headings, one example per section, and a 3-line summary. Add a Latin transliteration of the title.", ["polyglot", "writer"], ["world", "odia", "assamese", "writing"]],
  ["Hinglish / Tanglish content", "Code-mixed, the way people talk.", "@social @polyglot Write {{count}} {{type}} for {{topic}} in natural {{mix}} (Hinglish/Tanglish/Benglish) the way {{audience}} actually text — casual, funny where fitting, no forced purity. Add hashtags.", ["social", "polyglot"], ["world", "hinglish", "tanglish", "social"]],

  // ── Europe ───────────────────────────────────────────────────────────────────
  ["Español — artículo o blog", "Spanish article (neutral or regional).", "@polyglot @writer Escribe un {{type}} de {{words}} palabras sobre {{topic}} para {{audience}}, en español {{variety}} (neutro, de México, de España, rioplatense…). Tono natural, subtítulos, un ejemplo concreto por sección y un resumen final de tres líneas.", ["polyglot", "writer"], ["world", "spanish", "español", "writing"]],
  ["Español — correo profesional", "Spanish business email.", "@polyglot @email Redacta un correo profesional a {{recipient}} sobre {{situation}} con el objetivo de {{goal}}. Registro formal pero cercano (usted), asunto claro, petición concreta y cierre cordial. Incluye una versión breve para WhatsApp.", ["polyglot", "email"], ["world", "spanish", "email"]],
  ["Français — article ou billet", "French article/blog.", "@polyglot @writer Rédige un {{type}} de {{words}} mots sur {{topic}} pour {{audience}}, en français {{variety}} (de France, du Québec, d'Afrique francophone). Style fluide, intertitres, un exemple concret par partie, et une conclusion de trois lignes.", ["polyglot", "writer"], ["world", "french", "français", "writing"]],
  ["Français — lettre de motivation", "French cover letter.", "@polyglot @career Rédige une lettre de motivation pour le poste de {{role}} chez {{company}}. Mon parcours : {{background}}. Structure vous/moi/nous, accroche spécifique, trois réalisations chiffrées, formule de politesse adaptée. 300 mots maximum.", ["polyglot", "career"], ["world", "french", "career"]],
  ["Deutsch — Artikel oder Blogbeitrag", "German article/blog.", "@polyglot @writer Schreibe einen {{type}} mit {{words}} Wörtern über {{topic}} für {{audience}}. Natürliches Deutsch (keine Übersetzung aus dem Englischen), Zwischenüberschriften, ein konkretes Beispiel pro Abschnitt und ein dreizeiliges Fazit. Sie- oder Du-Form: {{form}}.", ["polyglot", "writer"], ["world", "german", "deutsch", "writing"]],
  ["Deutsch — Geschäftsbrief / E-Mail", "German business correspondence.", "@polyglot @email Verfasse eine geschäftliche E-Mail an {{recipient}} zum Thema {{situation}} mit dem Ziel {{goal}}. Höflich, klar, DIN-5008-nahe Struktur, präzise Bitte mit Frist. Danach eine kürzere, lockere Variante.", ["polyglot", "email"], ["world", "german", "email"]],
  ["Português — artigo ou post", "Portuguese (BR/PT) article.", "@polyglot @writer Escreva um {{type}} de {{words}} palavras sobre {{topic}} para {{audience}}, em português {{variety}} (do Brasil ou de Portugal). Linguagem natural, subtítulos, um exemplo concreto por seção e uma conclusão de três linhas.", ["polyglot", "writer"], ["world", "portuguese", "português", "writing"]],
  ["Italiano — articolo o post", "Italian article/blog.", "@polyglot @writer Scrivi un {{type}} di {{words}} parole su {{topic}} per {{audience}}. Italiano naturale e scorrevole, sottotitoli, un esempio concreto per sezione e una conclusione di tre righe.", ["polyglot", "writer"], ["world", "italian", "italiano", "writing"]],
  ["Nederlands — artikel of blog", "Dutch article/blog.", "@polyglot @writer Schrijf een {{type}} van {{words}} woorden over {{topic}} voor {{audience}}. Natuurlijk Nederlands, tussenkoppen, één concreet voorbeeld per deel en een samenvatting van drie regels.", ["polyglot", "writer"], ["world", "dutch", "nederlands", "writing"]],
  ["Русский — статья или пост", "Russian article/blog.", "@polyglot @writer Напиши {{type}} объёмом {{words}} слов на тему «{{topic}}» для {{audience}}. Живой, естественный русский язык, подзаголовки, по одному конкретному примеру в каждом разделе и вывод в три строки.", ["polyglot", "writer"], ["world", "russian", "русский", "writing"]],
  ["Українська — стаття", "Ukrainian article.", "@polyglot @writer Напиши {{type}} обсягом {{words}} слів на тему «{{topic}}» для {{audience}}. Природна сучасна українська, підзаголовки, один конкретний приклад у кожному розділі та висновок на три рядки.", ["polyglot", "writer"], ["world", "ukrainian", "writing"]],
  ["Polski — artykuł", "Polish article.", "@polyglot @writer Napisz {{type}} o długości {{words}} słów na temat {{topic}} dla {{audience}}. Naturalna polszczyzna, śródtytuły, jeden konkretny przykład w każdej części i trzywersowe podsumowanie.", ["polyglot", "writer"], ["world", "polish", "writing"]],
  ["Türkçe — makale veya blog", "Turkish article/blog.", "@polyglot @writer {{audience}} için {{topic}} hakkında {{words}} kelimelik bir {{type}} yaz. Doğal Türkçe, ara başlıklar, her bölümde somut bir örnek ve üç satırlık bir sonuç.", ["polyglot", "writer"], ["world", "turkish", "türkçe", "writing"]],
  ["Ελληνικά — άρθρο", "Greek article.", "@polyglot @writer Γράψε ένα {{type}} {{words}} λέξεων για το θέμα «{{topic}}» για {{audience}}. Φυσικά ελληνικά, υπότιτλοι, ένα συγκεκριμένο παράδειγμα ανά ενότητα και συμπέρασμα τριών γραμμών.", ["polyglot", "writer"], ["world", "greek", "writing"]],
  ["Svenska / Norsk / Dansk — artikel", "Scandinavian article.", "@polyglot @writer Skriv en {{type}} på {{words}} ord om {{topic}} för {{audience}} på {{language}} (svenska, norsk eller dansk). Naturligt språk, mellanrubriker, ett konkret exempel per del och en sammanfattning på tre rader.", ["polyglot", "writer"], ["world", "swedish", "norwegian", "danish", "writing"]],

  // ── Middle East & Africa ─────────────────────────────────────────────────────
  ["العربية — مقال أو تدوينة", "Arabic article (MSA or dialect).", "@polyglot @writer اكتب {{type}} من {{words}} كلمة عن {{topic}} موجهاً إلى {{audience}}، بالعربية {{variety}} (الفصحى الحديثة أو لهجة محددة). أسلوب طبيعي، عناوين فرعية، مثال ملموس في كل قسم، وخلاصة من ثلاثة أسطر.", ["polyglot", "writer"], ["world", "arabic", "العربية", "writing"]],
  ["العربية — رسالة رسمية", "Arabic formal letter/email.", "@polyglot @email اكتب رسالة رسمية إلى {{recipient}} بخصوص {{situation}} بهدف {{goal}}: تحية مناسبة، عرض واضح، طلب محدد بموعد، وخاتمة مهذبة. ثم نسخة مختصرة مناسبة للواتساب.", ["polyglot", "email"], ["world", "arabic", "email"]],
  ["فارسی — مقاله", "Persian article.", "@polyglot @writer یک {{type}} {{words}} کلمه‌ای دربارهٔ {{topic}} برای {{audience}} به فارسی روان بنویس: زیرعنوان‌ها، یک مثال ملموس در هر بخش، و جمع‌بندی سه‌خطی در پایان.", ["polyglot", "writer"], ["world", "persian", "farsi", "writing"]],
  ["עברית — מאמר", "Hebrew article.", "@polyglot @writer כתוב {{type}} באורך {{words}} מילים על {{topic}} עבור {{audience}}. עברית טבעית ועדכנית, כותרות משנה, דוגמה קונקרטית בכל חלק וסיכום בן שלוש שורות.", ["polyglot", "writer"], ["world", "hebrew", "writing"]],
  ["Kiswahili — makala", "Swahili article.", "@polyglot @writer Andika {{type}} ya maneno {{words}} kuhusu {{topic}} kwa ajili ya {{audience}}. Kiswahili sanifu na cha kawaida, vichwa vidogo, mfano halisi katika kila sehemu, na muhtasari wa mistari mitatu mwishoni.", ["polyglot", "writer"], ["world", "swahili", "kiswahili", "writing"]],
  ["Hausa / Yorùbá / Igbo / Amharic — article", "West & East African languages.", "@polyglot @writer Write a {{words}}-word {{type}} on {{topic}} in {{language}} (Hausa, Yorùbá, Igbo, Amharic, Zulu, Somali…) for {{audience}}: natural register, sub-headings, a local example per section, a 3-line summary, and an English gloss of the title.", ["polyglot", "writer"], ["world", "african-languages", "writing"]],

  // ── East & Southeast Asia ────────────────────────────────────────────────────
  ["中文 — 文章或博客", "Chinese (Simplified) article.", "@polyglot @writer 请以{{audience}}为读者，围绕“{{topic}}”写一篇{{words}}字的{{type}}。语言自然地道（避免翻译腔），使用小标题，每部分给出一个具体例子，结尾用三句话总结。", ["polyglot", "writer"], ["world", "chinese", "中文", "writing"]],
  ["中文 — 商务邮件", "Chinese business email.", "@polyglot @email 请写一封发给{{recipient}}的商务邮件，主题是{{situation}}，目标是{{goal}}。称呼得体、要点清晰、请求具体并注明期限、结尾礼貌。另附一个适合微信发送的简短版本。", ["polyglot", "email"], ["world", "chinese", "email"]],
  ["繁體中文 — 文章", "Traditional Chinese article (TW/HK).", "@polyglot @writer 請以{{audience}}為讀者，針對「{{topic}}」撰寫一篇{{words}}字的{{type}}（{{variety}}：台灣或香港用語）。文字自然、使用小標題、每段附一個具體例子，最後以三句話總結。", ["polyglot", "writer"], ["world", "chinese-traditional", "writing"]],
  ["日本語 — 記事・ブログ", "Japanese article/blog.", "@polyglot @writer {{audience}}向けに「{{topic}}」について{{words}}字の{{type}}を書いてください。自然な日本語（翻訳調を避ける）、小見出し、各セクションに具体例を一つ、最後に3行のまとめ。文体は{{style}}（です・ます／だ・である）。", ["polyglot", "writer"], ["world", "japanese", "日本語", "writing"]],
  ["日本語 — ビジネスメール", "Japanese business email (keigo).", "@polyglot @email {{recipient}}宛てに、{{situation}}について{{goal}}を目的としたビジネスメールを作成してください。適切な敬語、件名、要件の明確化、期限付きの依頼、結びの挨拶を含めてください。社内向けの簡潔版も添えてください。", ["polyglot", "email"], ["world", "japanese", "email", "keigo"]],
  ["한국어 — 글/블로그", "Korean article/blog.", "@polyglot @writer {{audience}}을(를) 대상으로 '{{topic}}'에 관한 {{words}}자 분량의 {{type}}을(를) 써 주세요. 번역투 없는 자연스러운 한국어, 소제목, 각 부분마다 구체적인 예시 하나, 마지막에 세 줄 요약. 문체: {{style}} (해요체/합쇼체).", ["polyglot", "writer"], ["world", "korean", "한국어", "writing"]],
  ["Bahasa Indonesia — artikel", "Indonesian article/blog.", "@polyglot @writer Tulis {{type}} sepanjang {{words}} kata tentang {{topic}} untuk {{audience}}. Bahasa Indonesia yang alami ({{register}}: baku atau santai), subjudul, satu contoh konkret per bagian, dan ringkasan tiga baris di akhir.", ["polyglot", "writer"], ["world", "indonesian", "bahasa", "writing"]],
  ["Bahasa Melayu — artikel", "Malay article.", "@polyglot @writer Tulis {{type}} sepanjang {{words}} patah perkataan tentang {{topic}} untuk {{audience}}. Bahasa Melayu yang semula jadi, subtajuk, satu contoh konkrit setiap bahagian, dan ringkasan tiga baris di akhir.", ["polyglot", "writer"], ["world", "malay", "writing"]],
  ["Tiếng Việt — bài viết", "Vietnamese article.", "@polyglot @writer Viết một {{type}} dài {{words}} từ về {{topic}} dành cho {{audience}}. Tiếng Việt tự nhiên, có tiêu đề phụ, mỗi phần một ví dụ cụ thể và phần kết ba dòng.", ["polyglot", "writer"], ["world", "vietnamese", "writing"]],
  ["ภาษาไทย — บทความ", "Thai article.", "@polyglot @writer เขียน{{type}}ความยาว {{words}} คำ เกี่ยวกับ {{topic}} สำหรับ {{audience}} ใช้ภาษาไทยที่เป็นธรรมชาติ มีหัวข้อย่อย ยกตัวอย่างที่เป็นรูปธรรมในแต่ละส่วน และสรุปสามบรรทัดตอนท้าย", ["polyglot", "writer"], ["world", "thai", "writing"]],
  ["Filipino — artikulo", "Filipino/Tagalog article.", "@polyglot @writer Sumulat ng {{type}} na may {{words}} salita tungkol sa {{topic}} para sa {{audience}}. Natural na Filipino (maaaring may Taglish kung angkop), may mga subheading, isang konkretong halimbawa bawat bahagi, at tatlong-linyang buod sa dulo.", ["polyglot", "writer"], ["world", "filipino", "tagalog", "writing"]],
  ["සිංහල / नेपाली / မြန်မာ — article", "Sinhala, Nepali, Burmese, Khmer, Lao.", "@polyglot @writer Write a {{words}}-word {{type}} on {{topic}} in {{language}} (Sinhala, Nepali, Burmese, Khmer or Lao) for {{audience}}: natural register, sub-headings, one local example per section, a 3-line summary, and a Latin transliteration of the title.", ["polyglot", "writer"], ["world", "sinhala", "nepali", "burmese", "writing"]],

  // ── Craft across languages ───────────────────────────────────────────────────
  ["Poetry in your language", "Native forms, not translated sonnets.", "@poet @polyglot Write a poem about {{theme}} in {{language}} using a form native to that tradition (e.g., ghazal, haiku, venba, doha, décima, pantun, sijo). State the form's rules, honour them, and give a line-by-line English gloss.", ["poet", "polyglot"], ["world", "multilingual", "poetry"]],
  ["Children's story in any language", "Simple, rhythmic, local.", "@storyteller @polyglot Write a 400-word children's story in {{language}} for ages {{age}} about {{theme}}, set in a place the child would recognise, with repetition, a gentle lesson, and 5 vocabulary words explained at the end.", ["storyteller", "polyglot"], ["world", "multilingual", "children"]],
  ["News summary in my language", "Global news, local words.", "@journalist @translator Summarise this article in {{language}} in 150 words for a general reader: neutral tone, key facts, who/what/when/where/why, and one sentence of context. Keep names in original script plus transliteration.\n\n{{article}}", ["journalist", "translator"], ["world", "multilingual", "news"]],
  ["Product description, localised", "E-commerce copy per market.", "@copywriter @translator Write a product description for {{product}} in {{language}} for the {{market}} market: benefit-led opening, 5 bullets, sizing/units in local conventions, a trust line, and 3 SEO keywords in that language.", ["copywriter", "translator"], ["world", "multilingual", "ecommerce", "copywriting"]],
  ["Song lyrics in my language", "Singable, with rhyme scheme.", "@poet @polyglot Write song lyrics in {{language}} about {{theme}} in the style of {{genre}}: 2 verses, chorus, bridge; consistent syllable counts; note the rhyme scheme; and mark stressed syllables in the chorus.", ["poet", "polyglot"], ["world", "multilingual", "lyrics", "music"]],
  ["Speech in my language", "Stage-ready, culturally apt.", "@speech @polyglot Write a {{minutes}}-minute speech in {{language}} for {{occasion}} to {{audience}}: culturally appropriate greeting, a story, a proverb from that language explained, one clear message, and a memorable close. Mark pauses.", ["speech", "polyglot"], ["world", "multilingual", "speech"]],
  ["Proofread in any language", "Native-speaker edit.", "@editor @polyglot Proofread and lightly edit this text in its own language: fix grammar, spelling, punctuation and unnatural phrasing; keep the author's voice. Return the corrected text, then a list of changes with one-line explanations in {{explain_in}}.\n\n{{text}}", ["editor", "polyglot"], ["world", "multilingual", "editing"]],
  ["Dialect & register switch", "Formal ↔ casual ↔ regional.", "@polyglot Rewrite this {{language}} text in three registers: formal/official, everyday conversational, and {{regional}} regional flavour. Explain the 5 biggest differences (vocabulary, particles, honorifics, verb forms).\n\n{{text}}", ["polyglot"], ["world", "multilingual", "register"]],
  ["Learn to write in a new script", "Practice plan for a script.", "@polyglot @tutor I want to learn to read and write {{script}} (e.g., Devanagari, Arabic, Hangul, Kana, Cyrillic, Tamil). Give a 14-day plan: letter groups per day, mnemonics, 5 practice words each day, and a mini-test on day 7 and 14.", ["polyglot", "tutor"], ["world", "multilingual", "scripts", "learning"]],
  ["Idioms across languages", "Say it like a local.", "@polyglot For the English idea '{{idea}}', give the natural equivalent idiom/expression in Tamil, Hindi, Spanish, French, German, Arabic, Chinese, Japanese, Korean and Russian — with literal meaning, usage note, and when it would sound odd.", ["polyglot"], ["world", "multilingual", "idioms"]],
];
