import type { SeedTuple } from "./types";

export const writing: SeedTuple[] = [
  ["Blog post from bullets", "Structured, concrete, 900 words.", "@writer Turn these bullet points into a 900-word blog post with a hook, clear sub-headings, one concrete example per section and a takeaway box at the end.\n\n{{bullets}}", ["writer"], ["writing", "blog"]],
  ["Ruthless editor", "Cut 30% without losing meaning.", "@editor Edit this text: cut at least 30%, fix grammar, tighten sentences, remove hedging and clichés, keep my voice. Show the edited version, then a short list of the patterns you fixed.\n\n{{text}}", ["editor"], ["writing", "editing"]],
  ["Short story from a prompt", "Character, want, obstacle, turn.", "@storyteller Write a 1,200-word short story from: {{premise}}. One POV, a clear want and obstacle, a turn in the middle, an earned ending. No epilogue moralising.", ["storyteller"], ["writing", "fiction"]],
  ["Wedding / farewell speech", "Warm, funny, memorable close.", "@speech Write a 4-minute {{occasion}} speech for {{person}}. Include one story, one laugh, one sincere line, rule of three, and a toast. Mark pauses. Notes: {{notes}}", ["speech"], ["writing", "speech"]],
  ["Poem in a chosen form", "Sonnet, ghazal, haiku, venba…", "@poet Write a {{form}} about {{theme}}. Honour the form's rules (state them), use concrete images, and offer an alternative last stanza.", ["poet"], ["writing", "poetry"]],
  ["Tamil kavithai", "நவீன தமிழ்க் கவிதை.", "@poet {{theme}} பற்றி ஒரு நவீன தமிழ்க் கவிதை எழுது — 12–16 வரிகள், படிமங்கள் நிறைந்த, மொழிபெயர்ப்பு போல அல்லாமல் இயல்பான தமிழில். முடிவில் ஒரு வரி பொருள் விளக்கம்.", ["poet"], ["writing", "tamil", "poetry"]],
  ["Hindi shayari", "चार शेर, एक भाव.", "@poet {{theme}} पर चार शेर लिखो (ग़ज़ल की तरह रदीफ़-क़ाफ़िया निभाते हुए)। हर शेर के नीचे एक पंक्ति में भाव समझाओ।", ["poet"], ["writing", "hindi", "poetry"]],
  ["Screenplay scene", "Proper format, subtext.", "@screenwriter Write a 2-page screenplay scene: {{situation}}. Proper sluglines and action lines, dialogue with subtext (characters don't say what they mean), and a button ending.", ["screenwriter"], ["writing", "screenplay"]],
  ["News article", "Inverted pyramid, attributed.", "@journalist Write a 500-word news article from these facts using the inverted pyramid, with attribution for every claim and a balanced opposing view. Headline + sub-head.\n\n{{facts}}", ["journalist"], ["writing", "journalism"]],
  ["Meeting minutes", "Decisions and actions with owners.", "@notes Turn this transcript into minutes: TL;DR, key points, decisions, action items (owner, due date), open questions. Preserve names and numbers exactly.\n\n{{transcript}}", ["notes"], ["writing", "productivity", "meetings"]],
  ["Difficult email", "Firm but kind.", "@email Draft an email to {{recipient}} about {{situation}}. Goal: {{goal}}. Tone: firm but kind. Give a short version and a longer version, plus 3 subject lines.", ["email"], ["writing", "email"]],
  ["Cover letter", "Specific, no clichés.", "@career Write a cover letter for {{role}} at {{company}}. My background: {{background}}. Open with a specific reason for this company, map 3 achievements to their needs with numbers, close with a confident ask. ≤300 words.", ["career"], ["writing", "career"]],
  ["Worldbuilding bible", "Consistent setting doc.", "@worldbuilder Create a worldbuilding bible for {{setting}}: geography, 3 cultures derived from it, economy, power structure, magic/tech system with costs, 5 factions (want/fear/resource), timeline, 5 adventure hooks.", ["worldbuilder"], ["writing", "worldbuilding", "rpg"]],
  ["Rewrite for a new audience", "Same facts, new reader.", "@writer Rewrite this for {{audience}} (e.g., 10-year-olds, executives, non-native readers): keep every fact, change vocabulary, sentence length and examples. Note what you changed and why.\n\n{{text}}", ["writer"], ["writing", "rewriting"]],
  ["Newsletter issue", "Curated, opinionated, scannable.", "@writer Write a newsletter issue for {{audience}} on {{theme}}: 1 lead insight (300 words), 3 curated items with one-line takes, 1 tool, 1 question for readers. Subject line ×3.", ["writer"], ["writing", "newsletter"]],
  ["Dialogue polish", "Make characters sound distinct.", "@screenwriter @editor Polish this dialogue: give each character a distinct voice, cut on-the-nose lines, add subtext and interruptions. Show before/after for the 5 biggest changes.\n\n{{dialogue}}", ["screenwriter", "editor"], ["writing", "fiction", "dialogue"]],
  ["Plain-language rewrite", "Legal/medical → plain English.", "@editor Rewrite this into plain language (grade-8 reading level) without losing accuracy. Define any term you must keep. Return the rewrite and a glossary.\n\n{{text}}", ["editor"], ["writing", "plain-language"]],
  ["Song lyrics", "Verse/chorus/bridge, singable.", "@poet Write song lyrics about {{theme}} in {{genre}}: 2 verses, chorus, bridge. Keep syllable counts consistent per section, note the rhyme scheme, and suggest a chord progression.", ["poet"], ["writing", "music", "lyrics"]],
  ["Translate with register notes", "Faithful, natural, annotated.", "@translator Translate into {{language}} faithfully and naturally. Then list 5 places where a literal translation would sound wrong and what you did instead.\n\n{{text}}", ["translator"], ["writing", "translation"]],
  ["Grant / proposal", "Problem, approach, impact, budget.", "@writer @accountant Write a proposal for {{project}} to {{funder}}: need statement with data, objectives (SMART), approach, timeline table, budget in ₹ with justification, evaluation plan, sustainability.", ["writer", "accountant"], ["writing", "grants", "nonprofit"]],
];
